#ifndef _CONFIG_H
#define _CONFIG_H

#define APPLICATION_NAME L"MyGame"
#define DEFAULT_WINDOWED_SCREEN_WIDTH 960
#define DEFAULT_WINDOWED_SCREEN_HEIGHT 540
#define FULLSCREEN false

#define SCREEN_DEPTH 1000.0f
#define SCREEN_NEAR 0.1f

#define VSYNC_ENABLED true
#define SHOW_CURSOR true

#endif